#!/usr/bin/env node
// Committed line counter for Material Router. Prints the exact table releases
// publish. Run `npm run count` (human table) or `npm run count -- --markdown`
// (markdown table consumed verbatim by the release workflow and the README).
//
// What is counted, stated rather than implied:
//   - Excluded entirely: node_modules, dist, out, .git, build icons (binary
//     outputs), .vscode/.idea scratch, package-lock.json (generated),
//     docs/articles/index.json (generated by npm run docs-index).
//   - Buckets assign every counted file to exactly one row; anything matching
//     no predicate lands in "(unmatched)" so a total can never quietly lose a
//     directory.
//   - Attribution counts SURVIVING lines via git blame, never log churn: a
//     line belongs to whoever introduced the change that still exists. A line
//     is agent-written when its introducing commit carries the
//     "Co-Authored-By: Claude Fable 5" trailer or was authored by the
//     automation identity itself (Claude Fable 5 <noreply@anthropic.com>);
//     everything else is human. Lines newer than the last commit are reported
//     separately as uncommitted so the arithmetic always closes.
//
// Self-consistency: bucket totals must equal the blame-attributed sums to the
// line. A mismatch throws instead of publishing two numbers that disagree.

import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToRoot } from './lib-root.mjs';

const ROOT = fileURLToRoot(import.meta.url);
const MARKDOWN = process.argv.includes('--markdown') || process.argv.includes('--md');

const EXCLUDE_DIRS = new Set(['node_modules', 'dist', 'out', '.git', 'build', '.vscode', '.idea']);
const EXCLUDE_FILES = new Set(['package-lock.json']);

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    let st;
    try { st = statSync(p); } catch { continue; }
    if (st.isDirectory()) {
      // In a linked worktree ".git" is a pointer FILE, not a directory, so
      // the file branch below must also refuse it.
      if (!EXCLUDE_DIRS.has(entry)) yield* walk(p);
    } else if (!EXCLUDE_FILES.has(entry) && entry !== '.git') {
      yield p;
    }
  }
}

/** Cheap binary sniff: a NUL byte means "not source", count nothing. */
function looksBinary(buffer) {
  const end = Math.min(buffer.length, 8192);
  for (let i = 0; i < end; i++) {
    if (buffer[i] === 0) return true;
  }
  return false;
}

// Ordered bucket rules. First match wins; order matters because e.g. a CSS
// file under site/ must land in styles while its markdown neighbours land in
// docs. tests/ is matched first so a future suite can never hide inside a
// broader bucket - today it is honestly empty, and the table says so.
const BUCKETS = [
  {
    key: 'tests',
    hint: 'test suites (none exist today - CI runs none by policy)',
    test: (r) => /(^|[\\/])(tests?|__tests__|spec)[\\/]/i.test(r) || /\.(test|spec)\.[cm]?js$/i.test(r),
  },
  {
    key: 'workflows',
    hint: 'GitHub Actions workflow definitions',
    test: (r) => r.startsWith(`.github${sep}`),
  },
  {
    key: 'styles',
    hint: 'all stylesheets',
    test: (r) => /\.css$/i.test(r),
  },
  {
    key: 'docs',
    hint: 'markdown documentation',
    test: (r) => (/\.md$/i.test(r)),
  },
  {
    key: 'site',
    hint: 'published site assets not covered above',
    test: (r) => r.startsWith(`site${sep}`),
  },
  {
    key: 'app-source',
    hint: 'main process, preload, renderer js/html',
    test: (r) => r.startsWith(`app${sep}`) || /\.(cjs|mjs|js|html)$/i.test(r),
  },
  {
    key: 'scripts',
    hint: 'build/count/release scripts and bat files',
    test: () => true, // catch-all so scripts/ and root bat/json always land somewhere named
  },
];

function bucketFor(relPath) {
  return BUCKETS.find((b) => b.test(relPath)) ?? null;
}

// ---------------------------------------------------------------------------
// Git plumbing first: attribution must be defined before the counting walk.
// ---------------------------------------------------------------------------

let gitAvailable = true;
try {
  execFileSync('git', ['rev-parse', '--is-inside-work-tree'], { cwd: ROOT, stdio: 'ignore' });
} catch {
  gitAvailable = false;
}

/**
 * Commit metadata: sha -> agent?. A commit is agent-authored when its message
 * carries the project's agent co-author trailer or when the commit author IS
 * the automation identity. The rule is printed with the results so the number
 * can be checked rather than trusted.
 */
const commitAgent = new Map();
if (gitAvailable) {
  // Field separators must be characters that cannot appear in commit text,
  // built from char codes so this source file stays printable ASCII.
  const SEP_FIELD = String.fromCharCode(1);
  const SEP_COMMIT = String.fromCharCode(2);
  let raw = '';
  try {
    raw = execFileSync(
      'git',
      ['log', '--all', `--format=%H${SEP_FIELD}%an${SEP_FIELD}%ae${SEP_FIELD}%B${SEP_COMMIT}`],
      { cwd: ROOT, maxBuffer: 64 * 1024 * 1024, encoding: 'utf8' },
    );
  } catch {
    gitAvailable = false;
  }
  if (gitAvailable && raw) {
    for (const chunk of raw.split(SEP_COMMIT)) {
      const body0 = chunk.replace(/^\n+/, '');
      if (!body0.trim()) continue;
      const [sha, name, email, ...bodyParts] = body0.split(SEP_FIELD);
      if (!sha || !/^[0-9a-f]{40}$/.test(sha.trim())) continue;
      const body = bodyParts.join(SEP_FIELD);
      const trailer = /^\s*Co-Authored-By:\s*Claude Fable 5\s*<noreply@anthropic\.com>\s*$/im.test(body);
      const authorIsAutomation = /claude fable 5/i.test(String(name ?? '')) || /^noreply@anthropic\.com$/i.test(String(email ?? ''));
      commitAgent.set(sha.trim(), Boolean(trailer || authorIsAutomation));
    }
  }
}

/** Blame one file; returns an array of per-line classes. */
function blameClasses(absPath, lineCount) {
  const classes = new Array(lineCount).fill('uncommitted');
  if (!gitAvailable) return classes;
  let out = '';
  try {
    out = execFileSync(
      'git',
      ['blame', '--line-porcelain', '--', absPath],
      { cwd: ROOT, maxBuffer: 64 * 1024 * 1024, encoding: 'utf8' },
    );
  } catch {
    return classes; // untracked or unreadable -> stays uncommitted
  }
  let idx = 0;
  for (const line of out.split('\n')) {
    const m = /^([0-9a-f]{40})\s+\d+\s+\d+/.exec(line);
    if (!m) continue;
    if (idx >= classes.length) break;
    const sha = m[1];
    classes[idx] = /^[0]+$/.test(sha) || !commitAgent.has(sha)
      ? 'uncommitted'
      : (commitAgent.get(sha) ? 'agent' : 'human');
    idx += 1;
  }
  return classes;
}

// ---------------------------------------------------------------------------
// Counting walk
// ---------------------------------------------------------------------------

const rows = new Map(BUCKETS.map((b) => [b.key, { files: 0, lines: 0, nonBlank: 0, generated: 0 }]));
const unmatchedRow = { files: 0, lines: 0, nonBlank: 0, generated: 0 };
const byBucketAttribution = new Map([...rows.keys()].map((k) => [k, { agent: 0, human: 0, uncommitted: 0 }]));
byBucketAttribution.set('(unmatched)', { agent: 0, human: 0, uncommitted: 0 });

/** rel path -> array of per-line classes ('agent' | 'human' | 'uncommitted') */
const attribution = new Map();

for (const abs of walk(ROOT)) {
  const rel = relative(ROOT, abs);
  // Generated artifacts are excluded outright even though the walk already
  // avoids their directories; keep the guard explicit next to the rules.
  if (rel.endsWith('index.json') && rel.includes(`docs${sep}articles`)) continue;
  let buffer;
  try { buffer = readFileSync(abs); } catch { continue; }
  // Binary outputs (images, icons) are excluded and stated, not silently
  // mis-decoded into a nonsense line count.
  if (looksBinary(buffer)) continue;
  const text = buffer.toString('utf8');
  const lines = text.split(/\r\n|\n|\r/);
  // Drop a phantom trailing line caused only by a final newline.
  if (lines.length && lines[lines.length - 1] === '') lines.pop();
  const nonBlank = lines.filter((l) => l.trim() !== '').length;

  const bucket = bucketFor(rel);
  const target = bucket ? rows.get(bucket.key) : unmatchedRow;
  target.files += 1;
  target.lines += lines.length;
  target.nonBlank += nonBlank;

  const classes = blameClasses(abs, lines.length);
  attribution.set(rel, classes);
  const acc = byBucketAttribution.get(bucket ? bucket.key : '(unmatched)');
  for (const c of classes) acc[c] += 1;
}

// ---------------------------------------------------------------------------
// Aggregation + self-consistency assertions
// ---------------------------------------------------------------------------

const totals = { agent: 0, human: 0, uncommitted: 0 };
for (const acc of byBucketAttribution.values()) {
  totals.agent += acc.agent;
  totals.human += acc.human;
  totals.uncommitted += acc.uncommitted;
}
let attributedLines = 0;
for (const classes of attribution.values()) attributedLines += classes.length;

// Assertion 1: every counted line is accounted for exactly once by class.
const bucketLineSum = [...rows.values()].reduce((a, r) => a + r.lines, 0) + unmatchedRow.lines;
if (attributedLines !== bucketLineSum) {
  throw new Error(
    `count-lines self-check failed: ${bucketLineSum} lines bucketed but ${attributedLines} lines blamed. `
    + 'The trailing-newline handling or bucket rules disagree with the blame pass - fix before publishing.',
  );
}
// Assertion 2: per-bucket class sums equal the bucket's declared line count.
for (const [key, acc] of byBucketAttribution) {
  const declared = key === '(unmatched)' ? unmatchedRow.lines : rows.get(key).lines;
  const summed = acc.agent + acc.human + acc.uncommitted;
  if (declared !== summed) {
    throw new Error(
      `count-lines self-check failed for bucket "${key}": ${declared} lines declared vs ${summed} attributed.`,
    );
  }
}

const grandTotal = {
  files: [...rows.values()].reduce((a, r) => a + r.files, 0) + unmatchedRow.files,
  lines: bucketLineSum,
  nonBlank: [...rows.values()].reduce((a, r) => a + r.nonBlank, 0) + unmatchedRow.nonBlank,
};
const generatedTotal = [...rows.values()].reduce((a, r) => a + r.generated, 0) + unmatchedRow.generated;

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

const fmt = (n) => n.toLocaleString('en-US');

if (MARKDOWN) {
  console.log('| Bucket | Files | Lines | Non-blank | Agent | Human | Uncommitted |');
  console.log('| --- | ---: | ---: | ---: | ---: | ---: | ---: |');
  for (const [key, v] of [...rows.entries(), ['(unmatched)', unmatchedRow]]) {
    const a = byBucketAttribution.get(key);
    console.log(`| ${key} | ${fmt(v.files)} | ${fmt(v.lines)} | ${fmt(v.nonBlank)} | ${fmt(a.agent)} | ${fmt(a.human)} | ${fmt(a.uncommitted)} |`);
  }
  console.log(`| **TOTAL** | ${fmt(grandTotal.files)} | ${fmt(grandTotal.lines)} | ${fmt(grandTotal.nonBlank)} | ${fmt(totals.agent)} | ${fmt(totals.human)} | ${fmt(totals.uncommitted)} |`);
  console.log('');
  console.log(`Generated lines within counted files: ${fmt(generatedTotal)}. Excluded entirely: node_modules, dist and build output, binary icon assets, package-lock.json (lockfile), docs/articles/index.json (generated docs index), .vscode/.idea scratch.`);
  console.log('');
  console.log('Attribution counts surviving lines only (git blame): agent = introducing commit carries "Co-Authored-By: Claude Fable 5" or its author is the automation identity; everything else is human; work newer than the last commit is listed as uncommitted.');
  process.exit(0);
}

const order = [...rows.entries(), ['(unmatched)', unmatchedRow]];
const w = Math.max(...order.map(([k]) => k.length));
console.log('Material Router line count');
console.log('');
console.log(`${'bucket'.padEnd(w)}  files      lines   non-blank    agent    human  uncomm.`);
console.log('-'.repeat(w + 62));
for (const [key, v] of order) {
  const a = byBucketAttribution.get(key);
  console.log(
    `${key.padEnd(w)}  ${String(v.files).padStart(5)}  ${String(v.lines).padStart(8)}  ${String(v.nonBlank).padStart(9)}  ${String(a.agent).padStart(7)}  ${String(a.human).padStart(7)}  ${String(a.uncommitted).padStart(7)}`,
  );
}
console.log('-'.repeat(w + 62));
console.log(
  `${'TOTAL'.padEnd(w)}  ${String(grandTotal.files).padStart(5)}  ${String(grandTotal.lines).padStart(8)}  ${String(grandTotal.nonBlank).padStart(9)}  ${String(totals.agent).padStart(7)}  ${String(totals.human).padStart(7)}  ${String(totals.uncommitted).padStart(7)}`,
);
console.log('');
console.log(`Generated lines within counted files: ${fmt(generatedTotal)}.`);
console.log('Excluded: node_modules, dist, out, .git, build icons (binaries), package-lock.json, docs/articles/index.json.');
console.log('Attribution rule: agent = introducing commit carries "Co-Authored-By: Claude Fable 5" or the author is the automation identity; surviving lines only (git blame); uncommitted lines listed separately.');
console.log(`Self-check ok: bucketed lines (${fmt(bucketLineSum)}) == blamed lines (${fmt(attributedLines)}).`);
