// Purpose: English strings for the Toolbox lane (file converter + local
// Ollama suite manager). Facts stay exact at every funny level; humour styles
// the voice around them. Owned by the Utility lane.

export const en = {
  // ---- tabs -------------------------------------------------------------
  'utility.tab.converter': 'Converter',
  'utility.tab.ollama': 'Ollama',
  'utility.tab.guide': 'Guide',

  // ---- converter: source -------------------------------------------------
  'utility.src.choose': 'Choose file…',
  'utility.src.chooseMore': 'Add more files…',
  'utility.src.drop': 'Drop a file here',
  'utility.src.dropHint': 'Dropped files up to 64 MB are staged locally first; larger files use Choose file.',
  'utility.src.detecting': 'Inspecting bytes…',
  'utility.src.detected': 'Detected',
  'utility.src.confidence': 'Confidence',
  'utility.src.reasons': 'Why',
  'utility.src.clear': 'Clear selection',
  'utility.mergePick': 'Add merge inputs…',
  'utility.mergeList': 'Merge order',

  // ---- categories --------------------------------------------------------
  'utility.cat.documents': 'Documents / PDF',
  'utility.cat.images': 'Images',
  'utility.cat.audio': 'Audio',
  'utility.cat.video': 'Video',
  'utility.cat.archives': 'Archives',
  'utility.cat.structured': 'Structured data',
  'utility.cat.text': 'Code / Text',
  'utility.cat.binary': 'Binary encodings',

  // ---- adapter catalog ----------------------------------------------------
  'utility.adapter.search': 'Search converters…',
  'utility.adapter.none': 'No converter matches this filter.',
  'utility.adapter.lossy': 'Lossy / changes things',
  'utility.adapter.lossless': 'Lossless structure copy',
  'utility.adapter.bundled': 'Bundled engine',
  'utility.adapter.unbundled': 'Unavailable',
  'utility.adapter.notes': 'What this conversion does',
  'utility.adapter.requires': 'Before it runs',
  'utility.adapter.args': 'Options',
  'utility.adapter.pageOrderHint': 'Give every page index once, e.g. 2,0,1',
  'utility.adapter.sizesHint': 'Icon sizes to embed (px)',

  // ---- disclosure + destination -------------------------------------------
  'utility.disclosure.title': 'Before you convert',
  'utility.dest.saveAs': 'Save output as…',
  'utility.dest.pickFolder': 'Choose destination folder…',
  'utility.dest.none': 'Pick a destination first.',
  'utility.overwrite.title': 'Replace an existing file?',
  'utility.overwrite.body': '“{name}” already exists. Converting will replace its contents with the new output. This cannot be undone.',
  'utility.convert': 'Convert',
  'utility.convertQueued': 'Queued',

  // ---- queue ---------------------------------------------------------------
  'utility.queue.title': 'Batch queue',
  'utility.queue.empty': 'Nothing queued yet. Detected conversions land here.',
  'utility.queue.pause': 'Pause queue',
  'utility.queue.resume': 'Resume queue',
  'utility.queue.cancel': 'Cancel',
  'utility.queue.retry': 'Retry',
  'utility.queue.remove': 'Remove',
  'utility.queue.clearFinished': 'Clear finished',
  'utility.queue.pausedBadge': 'Paused',
  'utility.queue.concurrency': 'Runs up to 2 at once · resumable across restarts',
  'utility.state.pending': 'Waiting',
  'utility.state.converting': 'Converting',
  'utility.state.cancelling': 'Cancelling',
  'utility.state.done': 'Done',
  'utility.state.skipped': 'Skipped',
  'utility.state.failed': 'Failed',
  'utility.state.cancelled': 'Cancelled',
  'utility.state.interrupted': 'Interrupted by shutdown',

  // ---- notes -----------------------------------------------------------------
  'utility.notes.pdfStructural': 'Rebuilds the PDF page tree with renumbered objects; content streams are copied byte-for-byte.',
  'utility.notes.pdfMerge': 'Concatenates pages of every input into one document, preserving each page’s resources.',
  'utility.notes.pdfRotate': 'Sets the /Rotate flag on every page; page content itself is untouched.',
  'utility.notes.imgConvert': 'Rasterises through the canvas engine. JPEG adds compression artefacts; scaling resamples pixels; animation becomes a single frame.',
  'utility.notes.icoWrap': 'Wraps freshly rendered PNG layers into one .ico container. Sizes above the source resolution upscale softly.',
  'utility.notes.wavResample': 'Linear-interpolation resampling; bit-depth conversion quantises samples; channel change duplicates or drops channels instead of mixing.',
  'utility.notes.wavRaw': 'Strips the RIFF header and writes the raw sample bytes unchanged.',
  'utility.notes.rawWav': 'Adds a canonical 44-byte WAVE header around raw PCM using the options below.',
  'utility.notes.zipExtract': 'Extracts STORE and DEFLATE entries. Entry paths are sanitised: absolute paths, drive letters and “..” escapes are refused.',
  'utility.notes.zipCreate': 'Packs files into a classic ZIP (deflate when smaller). ZIP64, encryption and 4 GB+ single files are not written.',
  'utility.notes.yamlSubset': 'Writes block-style YAML: maps, sequences and scalars. Anchors, aliases, multi-document files, comments and tags are not preserved.',
  'utility.notes.yamlSubsetRead': 'Reads block-style YAML (maps, sequences, scalars). Flow style, anchors and multi-document input are outside the subset.',
  'utility.notes.tomlSubset': 'Writes scalar keys, one level of tables and arrays of tables. Deeper structures become JSON strings inside their field.',
  'utility.notes.tomlSubsetRead': 'Reads tables, arrays of tables and scalar/array values of the TOML subset.',
  'utility.notes.csvNest': 'One row per array element. Nested values are serialised as JSON strings inside their cell.',
  'utility.notes.csvTyped': 'Numbers, true/false and empty cells are typed on read; everything else stays a string.',
  'utility.notes.textEnc': 'Converts between UTF-8, UTF-16LE/BE and Latin-1 with BOM control, optionally normalising line endings. Latin-1 cannot represent characters beyond U+00FF (they become “?”).',
  'utility.notes.base64': 'Encodes the whole file as Base64, wrapped at 76 columns. Streaming, so large files are fine.',
  'utility.notes.hex': 'Encodes the whole file as lowercase hexadecimal. Streaming, so large files are fine.',
  'utility.notes.fromB64': 'Decodes Base64 (whitespace ignored). Input must be a whole number of 4-character groups.',
  'utility.notes.fromHex': 'Decodes hexadecimal (whitespace ignored). Input must contain an even number of hex digits.',

  // ---- unavailable reasons (visible, disabled) ---------------------------------
  'utility.unavailable.docx': 'No bundled DOCX layout engine: rendering Word documents to PDF needs a word processor this app does not carry.',
  'utility.unavailable.tiff': 'No bundled TIFF codec in the canvas engine.',
  'utility.unavailable.heic': 'No bundled HEIC/HEIF codec licence-free decoder ships with the app.',
  'utility.unavailable.audioCodec': 'No bundled MP3/OGG/FLAC/AAC decoder or encoder.',
  'utility.unavailable.videoCodec': 'Header inspection only. Transcoding video needs an external codec pack this app deliberately does not bundle.',
  'utility.unavailable.sevenZip': 'No bundled 7-Zip engine. The app writes plain ZIP archives instead.',
  'utility.unavailable.rar': 'RAR extraction needs the proprietary unrar library, which is not bundled.',

  // ---- requirements ------------------------------------------------------------
  'utility.req.pdfUnencrypted': 'The PDF must be unencrypted and must not use compressed object streams; both cases are detected and refused before anything runs.',

  // ---- errors -------------------------------------------------------------------
  'utility.err.prefix': 'Converter error',
  'utility.err.stageFailed': 'Could not stage the dropped file locally.',

  // ---- Ollama: status --------------------------------------------------------------
  'ollama.status.title': 'Service status',
  'ollama.status.refresh': 'Refresh status',
  'ollama.status.version': 'Version',
  'ollama.status.notRunning': 'Not reachable',
  'ollama.state.ok': 'Reachable',
  'ollama.state.unreachable': 'Nothing is listening on the local API port',
  'ollama.state.unhealthy': 'Port answered too slowly (unhealthy)',
  'ollama.state.error': 'Status check failed',
  'ollama.status.diskLow': 'Low free disk space beside your models folder',
  'ollama.action.startService': 'Install or start Ollama, then refresh',
  'ollama.action.checkService': 'Check the service and refresh',
  'ollama.action.retry': 'Try again',
  'ollama.trouble.open': 'Troubleshooting…',
  'ollama.trouble.title': 'Ollama troubleshooting',

  // ---- installed models ----------------------------------------------------------------
  'ollama.installed.title': 'Installed models',
  'ollama.installed.search': 'Search installed models…',
  'ollama.installed.empty': 'No models installed yet. Pull one from the Model Store below.',
  'ollama.installed.refresh': 'Refresh list',
  'ollama.filter.all': 'All',
  'ollama.filter.runningOnly': 'Running only',
  'ollama.sort.nameAsc': 'Name A→Z',
  'ollama.sort.sizeDesc': 'Largest first',
  'ollama.model.showInfo': 'Details',
  'ollama.model.chat': 'Chat',
  'ollama.model.delete': 'Delete model…',
  'ollama.model.deleteTitle': 'Delete this model?',
  'ollama.model.deleteBody': '“{name}” ({size}) will be removed from the local Ollama storage. Downloading it again later takes the same transfer as the first time.',
  'ollama.model.capabilities': 'Capabilities',
  'ollama.model.noCapabilities': 'No special capabilities reported.',
  'ollama.model.parameters': 'Parameters',
  'ollama.model.modelfile': 'Modelfile excerpt',

  // ---- Model Store ------------------------------------------------------------------------
  'ollama.store.title': 'Model Store (official library)',
  'ollama.store.search': 'Search the library…',
  'ollama.store.refresh': 'Refresh catalog now',
  'ollama.store.fresh': 'Catalog verified {age}',
  'ollama.store.stale': 'Catalog last verified {age} — older than a day',
  'ollama.store.never': 'Catalog never fetched — press refresh while online',
  'ollama.store.offline': 'Offline: showing the last verified copy only.',
  'ollama.store.ageHours': '{n}h ago',
  'ollama.store.justNow': 'just now',
  'ollama.store.empty': 'The stored catalog is empty. Refresh while online to fetch the official library.',
  'ollama.store.variants': 'Variants…',
  'ollama.store.variantsLoading': 'Fetching variant sizes…',
  'ollama.store.variantsError': 'Variant fetch failed: {error}',
  'ollama.store.addToCart': 'Add to cart',
  'ollama.store.inCart': 'In cart',
  'ollama.verdict.runsWell': 'Runs well',
  'ollama.verdict.runsWithLimits': 'Runs with limits',
  'ollama.verdict.unlikely': 'Unlikely',
  'ollama.verdict.unknown': 'Unknown',
  'ollama.evidence.title': 'Evidence',

  // ---- cart / pulls ---------------------------------------------------------------------------
  'ollama.cart.title': 'Cart & downloads',
  'ollama.cart.empty': 'Cart is empty. Add variants from the Model Store.',
  'ollama.cart.summary': '{count} item(s) · {size} to download · needs about {need} free disk · transferred over your network now',
  'ollama.cart.start': 'Start downloads',
  'ollama.cart.remove': 'Remove',
  'ollama.cart.cancel': 'Cancel download',
  'ollama.cart.retry': 'Retry',
  'ollama.cart.state.queued': 'Queued',
  'ollama.cart.state.pulling': 'Downloading',
  'ollama.cart.state.done': 'Done',
  'ollama.cart.state.failed': 'Failed',
  'ollama.cart.state.cancelled': 'Cancelled',
  'ollama.cart.parallel': 'Up to 2 downloads at once; finished models stay even if another fails.',

  // ---- chat ------------------------------------------------------------------------------------
  'ollama.chat.title': 'Local chat',
  'ollama.chat.new': 'New conversation',
  'ollama.chat.rename': 'Rename…',
  'ollama.chat.delete': 'Delete…',
  'ollama.chat.deleteTitle': 'Delete this conversation?',
  'ollama.chat.deleteBody': '“{name}” and its {messages} messages will be removed from local history. Export first if you want a copy.',
  'ollama.chat.export': 'Export (redacted)',
  'ollama.chat.exportNote': 'Export omits nothing you typed but carries no secrets — chats stay local and none exist.',
  'ollama.chat.sessions': 'Conversations',
  'ollama.chat.noSessions': 'No conversations yet.',
  'ollama.chat.model': 'Model',
  'ollama.chat.systemPrompt': 'System prompt',
  'ollama.chat.systemPlaceholder': 'Optional instructions the model receives first…',
  'ollama.chat.params': 'Generation parameters',
  'ollama.param.numPredict': 'Max output tokens (num_predict)',
  'ollama.param.temperature': 'Temperature',
  'ollama.param.topP': 'top_p',
  'ollama.param.topK': 'top_k',
  'ollama.param.repeatPenalty': 'repeat_penalty',
  'ollama.param.numCtx': 'Context window (num_ctx)',
  'ollama.chat.message': 'Message',
  'ollama.chat.placeholder': 'Ask the local model something…',
  'ollama.chat.send': 'Send',
  'ollama.chat.stop': 'Stop',
  'ollama.chat.regenerate': 'Regenerate',
  'ollama.chat.generating': 'Generating…',
  'ollama.chat.attach': 'Attach image',
  'ollama.chat.attachDisabled': 'Attachments disabled: this model does not report vision capability.',
  'ollama.chat.you': 'You',
  'ollama.chat.assistant': 'Assistant',
  'ollama.chat.errorPrefix': 'Generation stopped',

  // ---- harness -------------------------------------------------------------------------------------
  'ollama.harness.title': 'Harness launcher',
  'ollama.harness.intro': 'Launch a local program against a chosen model. Profiles are registered through a real file picker; arguments follow a strict schema.',
  'ollama.harness.launch': 'Launch…',
  'ollama.harness.register': 'Register profile…',
  'ollama.harness.delete': 'Delete…',
  'ollama.harness.restoreSnapshot': 'Restore snapshot…',
  'ollama.harness.profileName': 'Profile name',
  'ollama.harness.pickExe': 'Choose executable…',
  'ollama.harness.exeChosen': 'Executable: {exe}',
  'ollama.harness.args': 'Arguments (one per token)',
  'ollama.harness.argsHint': '{model} inserts the chosen model. Flags and plain tokens only.',
  'ollama.harness.cwd': 'Working directory (optional)',
  'ollama.harness.cwdBrowse': 'Browse…',
  'ollama.harness.envKeys': 'Environment variable NAMES to forward (values are taken from the environment and never shown)',
  'ollama.harness.save': 'Save profile',
  'ollama.harness.preflightTitle': 'Preflight review',
  'ollama.harness.preflightIntro': 'Exactly what will run:',
  'ollama.harness.envLine': '{key} (value redacted)',
  'ollama.harness.blockers': 'Blockers',
  'ollama.harness.launchBtn': 'Launch now',
  'ollama.harness.launched': 'Launched (pid {pid}, {health}).',
  'ollama.harness.launchBlocked': 'Not launched',
  'ollama.harness.rolledBack': 'Profile snapshot {id} restored automatically.',
  'ollama.harness.restoreTitle': 'Restore which snapshot?',
  'ollama.harness.restored': 'Profiles restored from {id}.',
  'ollama.harness.prebuiltTag': 'example',
};

export default en;
