// Purpose: 繁體中文（香港口語 flavour）strings for the Toolbox lane. Facts
// stay exact at every funny level; humour styles the voice around them.
// Owned by the Utility lane.

export const zh = {
  // ---- tabs -------------------------------------------------------------
  'utility.tab.converter': '檔案轉換',
  'utility.tab.ollama': 'Ollama',
  'utility.tab.guide': '指南',

  // ---- converter: source -------------------------------------------------
  'utility.src.choose': '揀檔案…',
  'utility.src.chooseMore': '再加多幾個檔案…',
  'utility.src.drop': '將檔案掣落呢度',
  'utility.src.dropHint': '掣入嚟嘅檔案會先暫存喺本機（上限 64 MB）；更大件嘅請用「揀檔案」。',
  'utility.src.detecting': '睇緊 bytes…',
  'utility.src.detected': '認到係',
  'utility.src.confidence': '信心',
  'utility.src.reasons': '點解',
  'utility.src.clear': '清空選擇',
  'utility.mergePick': '加合併來源…',
  'utility.mergeList': '合併次序',

  // ---- categories --------------------------------------------------------
  'utility.cat.documents': '文件 / PDF',
  'utility.cat.images': '圖像',
  'utility.cat.audio': '音訊',
  'utility.cat.video': '影片',
  'utility.cat.archives': '壓縮檔',
  'utility.cat.structured': '結構化資料',
  'utility.cat.text': '程式碼 / 文字',
  'utility.cat.binary': '二進制編碼',

  // ---- adapter catalog ----------------------------------------------------
  'utility.adapter.search': '搜尋轉換器…',
  'utility.adapter.none': '無轉換器符合呢個篩選。',
  'utility.adapter.lossy': '有損 / 會改嘢',
  'utility.adapter.lossless': '無損結構複製',
  'utility.adapter.bundled': '內置引擎',
  'utility.adapter.unbundled': '做唔到',
  'utility.adapter.notes': '呢個轉換實際會做啲乜',
  'utility.adapter.requires': '行之前要符合',
  'utility.adapter.args': '選項',
  'utility.adapter.pageOrderHint': '每個頁碼寫一次，例如 2,0,1',
  'utility.adapter.sizesHint': '要包入 icon 嘅尺寸 (px)',

  // ---- disclosure + destination -------------------------------------------
  'utility.disclosure.title': '撳轉換之前',
  'utility.dest.saveAs': '輸出儲存為…',
  'utility.dest.pickFolder': '揀輸出資料夾…',
  'utility.dest.none': '先揀個目的地。',
  'utility.overwrite.title': '覆蓋現有檔案？',
  'utility.overwrite.body': '「{name}」已經存在。轉換會用新輸出取代佢嘅內容，事後冇得返轉頭。',
  'utility.convert': '轉換',
  'utility.convertQueued': '已排隊',

  // ---- queue ---------------------------------------------------------------
  'utility.queue.title': '批次排隊',
  'utility.queue.empty': '仲未有未有嘢排隊。偵測到可以轉嘅嘢會自動落嚟呢度。',
  'utility.queue.pause': '暫停隊列',
  'utility.queue.resume': '繼續隊列',
  'utility.queue.cancel': '取消',
  'utility.queue.retry': '再嚟一次',
  'utility.queue.remove': '移除',
  'utility.queue.clearFinished': '清走完成咗嘅',
  'utility.queue.pausedBadge': '已暫停',
  'utility.queue.concurrency': '最多同時行兩個 · 重開 app 都接得住',
  'utility.state.pending': '排隊中',
  'utility.state.converting': '轉緊',
  'utility.state.cancelling': '取消緊',
  'utility.state.done': '完成',
  'utility.state.skipped': '跳過咗',
  'utility.state.failed': '失敗',
  'utility.state.cancelled': '已取消',
  'utility.state.interrupted': '熄機打斷咗',

  // ---- notes -----------------------------------------------------------------
  'utility.notes.pdfStructural': '重建 PDF 頁樹同重新編號物件；內容 stream 逐 byte 原封不動照抄。',
  'utility.notes.pdfMerge': '將每個輸入嘅頁串成一份文件，保留每一頁自己嘅資源。',
  'utility.notes.pdfRotate': '只係設定每頁嘅 /Rotate 旗標；頁面內容一毫子都冇掂過。',
  'utility.notes.imgConvert': '經 canvas 引擎 rasterise。JPEG 會有壓會有壓縮痕；縮放會重新取樣像素；動畫會變得返第一格。',
  'utility.notes.icoWrap': '將即場渲染嘅 PNG 圖層包入一個 .ico 容器。大過原圖嘅尺寸會柔和放大。',
  'utility.notes.wavResample': '線性插值重採樣；轉 bit depth 會量化；改聲道係直接複製或刪除，唔會混音。',
  'utility.notes.wavRaw': '剝走 RIFF header，raw sample bytes 一粒都唔變。',
  'utility.notes.rawWav': '用下面選項為 raw PCM 加返個標準 44-byte WAVE header。',
  'utility.notes.zipExtract': '解壓 STORE 同 DEFLATE 條目。路徑會消毒：絕對路徑、磁碟代號同「..」跳出一律拒收。',
  'utility.notes.zipCreate': '打包成傳統 ZIP（細嘅時候用 deflate）。ZIP64、加密、單檔 4 GB 以上都唔會寫。',
  'utility.notes.yamlSubset': '寫 block 式 YAML：map、sequence、純量。Anchor、alias、多文件、註解同 tag 全部唔保留。',
  'utility.notes.yamlSubsetRead': '只讀 block 式 YAML（map、sequence、純量）。Flow style、anchor、多文件唔喺支援範圍。',
  'utility.notes.tomlSubset': '寫純量 key、一層 table、table array。更深層嘅結構會變成 JSON 字串擺入欄位。',
  'utility.notes.tomlSubsetRead': '讀 TOML subset 嘅 table、table array 同純量/陣列值。',
  'utility.notes.csvNest': '一個陣列元素一行。巢狀值會 JSON 化做字串塞入格子。',
  'utility.notes.csvTyped': '數字、true/false 同空格會自動判型；其餘照字串處理。',
  'utility.notes.textEnc': 'UTF-8、UTF-16LE/BE、Latin-1 互轉，可控制 BOM 同統一行尾。Latin-1 表達唔到 U+00FF 以外字符（會變「?」）。',
  'utility.notes.base64': '成個檔案編碼做 Base64，每 76 字元斷行。串流處理，大檔都得。',
  'utility.notes.hex': '成個檔案編碼做小寫十六進制。串流處理，大檔都得。',
  'utility.notes.fromB64': '解码 Base64（忽略空白）。長度必須係 4 嘅倍數。',
  'utility.notes.fromHex': '解码十六進制（忽略空白）。位數必須係雙數。',

  // ---- unavailable reasons (visible, disabled) ---------------------------------
  'utility.unavailable.docx': '無內置 DOCX 排版引擎：Word 轉 PDF 需要一套文書處理器，app 冇帶。',
  'utility.unavailable.tiff': 'canvas 引擎無內置 TIFF codec。',
  'utility.unavailable.heic': 'App 冇帶免授權嘅 HEIC/HEIF 解碼器。',
  'utility.unavailable.audioCodec': '無內置 MP3/OGG/FLAC/AAC 編解碼器。',
  'utility.unavailable.videoCodec': '只讀 container header。轉片需要外部 codec 包，app 特意唔捆綁。',
  'utility.unavailable.sevenZip': '無內置 7-Zip 引擎。App 只會寫普通 ZIP。',
  'utility.unavailable.rar': 'RAR 解壓需要專利嘅 unrar library，冇捆綁。',

  // ---- requirements ------------------------------------------------------------
  'utility.req.pdfUnencrypted': 'PDF 必須未加密、亦唔可以用壓縮 object streams；兩種情況都會事先偵測並拒絕執行。',

  // ---- errors -------------------------------------------------------------------
  'utility.err.prefix': '轉換出錯',
  'utility.err.stageFailed': '暫存掣入嚟嘅檔案失敗。',

  // ---- Ollama: status --------------------------------------------------------------
  'ollama.status.title': '服務狀態',
  'ollama.status.refresh': '刷新狀態',
  'ollama.status.version': '版本',
  'ollama.status.notRunning': '連唔上',
  'ollama.state.ok': '連到',
  'ollama.state.unreachable': '本機 API port 無嘢聽緊',
  'ollama.state.unhealthy': 'Port 反應太慢（唔健康）',
  'ollama.state.error': '狀態檢查失敗',
  'ollama.status.diskLow': '模型資料夾所在磁碟嘅可用空間唔多',
  'ollama.action.startService': '安裝或者啟動 Ollama，然後刷新',
  'ollama.action.checkService': '檢查服務之後刷新',
  'ollama.action.retry': '再試一次',
  'ollama.trouble.open': '疑難排解…',
  'ollama.trouble.title': 'Ollama 疑難排解',

  // ---- installed models ----------------------------------------------------------------
  'ollama.installed.title': '已安裝模型',
  'ollama.installed.search': '搜尋已安裝模型…',
  'ollama.installed.empty': '仲未裝任何模型。去下面 Model Store 拉一個啦。',
  'ollama.installed.refresh': '刷新列表',
  'ollama.filter.all': '全部',
  'ollama.filter.runningOnly': '只看運行中',
  'ollama.sort.nameAsc': '名稱 A→Z',
  'ollama.sort.sizeDesc': '大至上至細',
  'ollama.model.showInfo': '詳情',
  'ollama.model.chat': '傾偈',
  'ollama.model.delete': '刪除模型…',
  'ollama.model.deleteTitle': '刪除呢個模型？',
  'ollama.model.deleteBody': '「{name}」（{size}）會由本機 Ollama 儲存移除。第日想再用就要重新下載成一次咁大份。',
  'ollama.model.capabilities': '能力',
  'ollama.model.noCapabilities': '冇回報特別能力。',
  'ollama.model.parameters': '參數',
  'ollama.model.modelfile': 'Modelfile 摘錄',

  // ---- Model Store ------------------------------------------------------------------------
  'ollama.store.title': 'Model Store（官方 library）',
  'ollama.store.search': '搜尋 library…',
  'ollama.store.refresh': '立即刷新 catalog',
  'ollama.store.fresh': 'Catalog 已驗證 {age}',
  'ollama.store.stale': 'Catalog 對上一次驗證係 {age} — 超過一日',
  'ollama.store.never': '從未攞過 catalog — 上網嗰陣撳刷新',
  'ollama.store.offline': '離線中：淨係顯示最後驗證嗰份。',
  'ollama.store.ageHours': '{n} 小時前',
  'ollama.store.justNow': '啱啱先',
  'ollama.store.empty': '存起嘅 catalog 係空嘅。上網嗰陣刷新就可以攞官方 library。',
  'ollama.store.variants': '睇變體…',
  'ollama.store.variantsLoading': '攞緊變體尺寸…',
  'ollama.store.variantsError': '攞變體失敗：{error}',
  'ollama.store.addToCart': '加入車仔',
  'ollama.store.inCart': '喺車仔入面',
  'ollama.verdict.runsWell': '行得好順',
  'ollama.verdict.runsWithLimits': '勉強行到',
  'ollama.verdict.unlikely': '好難行',
  'ollama.verdict.unknown': '唔知',
  'ollama.evidence.title': '證據',

  // ---- cart / pulls ---------------------------------------------------------------------------
  'ollama.cart.title': '車仔同下載',
  'ollama.cart.empty': '車仔係空嘅。去 Model Store 加變體。',
  'ollama.cart.summary': '{count} 件 · 要下載 {size} · 大約需要 {need} 磁碟空間 · 即刻會經你個網絡傳輸',
  'ollama.cart.start': '開始下載',
  'ollama.cart.remove': '移除',
  'ollama.cart.cancel': '取消下載',
  'ollama.cart.retry': '再嚟',
  'ollama.cart.state.queued': '排隊中',
  'ollama.cart.state.pulling': '下載緊',
  'ollama.cart.state.done': '完成',
  'ollama.cart.state.failed': '失敗',
  'ollama.cart.state.cancelled': '已取消',
  'ollama.cart.parallel': '最多兩個並行；第個失敗都唔會影響已完成嘅模型。',

  // ---- chat ------------------------------------------------------------------------------------
  'ollama.chat.title': '本機傾偈',
  'ollama.chat.new': '新對話',
  'ollama.chat.rename': '改名…',
  'ollama.chat.delete': '刪除…',
  'ollama.chat.deleteTitle': '刪除呢個對話？',
  'ollama.chat.deleteBody': '「{name}」同佢嘅 {messages} 句訊息會由本機歷史移除。想要副本就先 export。',
  'ollama.chat.export': '匯出（已消毒）',
  'ollama.chat.exportNote': '匯出包含你打過嘅所有嘢，但唔會有秘密——對話留喺本機，本身亦冇秘密存在。',
  'ollama.chat.sessions': '對話',
  'ollama.chat.noSessions': '仲未有對話。',
  'ollama.chat.model': '模型',
  'ollama.chat.systemPrompt': 'System prompt',
  'ollama.chat.systemPlaceholder': '畀模型最先收到嘅指示（可以留空）…',
  'ollama.chat.params': '生成參數',
  'ollama.param.numPredict': '最大輸出 token（num_predict）',
  'ollama.param.temperature': '溫度',
  'ollama.param.topP': 'top_p',
  'ollama.param.topK': 'top_k',
  'ollama.param.repeatPenalty': 'repeat_penalty',
  'ollama.param.numCtx': 'Context window（num_ctx）',
  'ollama.chat.message': '訊息',
  'ollama.chat.placeholder': '問吓個本機模型…',
  'ollama.chat.send': '送出',
  'ollama.chat.stop': '停',
  'ollama.chat.regenerate': '重新生成',
  'ollama.chat.generating': '諗緊…',
  'ollama.chat.attach': '附加圖片',
  'ollama.chat.attachDisabled': '附件停用：呢個模型冇回報 vision 能力。',
  'ollama.chat.you': '你',
  'ollama.chat.assistant': '助手',
  'ollama.chat.errorPrefix': '生成停咗',

  // ---- harness -------------------------------------------------------------------------------------
  'ollama.harness.title': 'Harness 啟動器',
  'ollama.harness.intro': '用指定模型啟動本機程式。Profile 要經真實檔案選擇器登記；參數跟嚴格 schema。',
  'ollama.harness.launch': '啟動…',
  'ollama.harness.register': '登記 profile…',
  'ollama.harness.delete': '刪除…',
  'ollama.harness.restoreSnapshot': '還原快照…',
  'ollama.harness.profileName': 'Profile 名',
  'ollama.harness.pickExe': '揀執行檔…',
  'ollama.harness.exeChosen': '執行檔：{exe}',
  'ollama.harness.args': '參數（一格一個 token）',
  'ollama.harness.argsHint': '{model} 會替換成所選模型。只接受旗同意普通 token。',
  'ollama.harness.cwd': '工作目錄（可選）',
  'ollama.harness.cwdBrowse': '瀏覽…',
  'ollama.harness.envKeys': '要轉發嘅環境變數「名稱」（數值由環境取，永遠唔顯示）',
  'ollama.harness.save': '儲存 profile',
  'ollama.harness.preflightTitle': '啟動前檢查',
  'ollama.harness.preflightIntro': '實際會行嘅嘢：',
  'ollama.harness.envLine': '{key}（數值已遮蔽）',
  'ollama.harness.blockers': '阻住嘅嘢',
  'ollama.harness.launchBtn': '即刻啟動',
  'ollama.harness.launched': '已啟動（pid {pid}，{health}）。',
  'ollama.harness.launchBlocked': '未啟動',
  'ollama.harness.rolledBack': 'Profile 快照 {id} 已自動還原。',
  'ollama.harness.restoreTitle': '還原邊個快照？',
  'ollama.harness.restored': 'Profiles 已由 {id} 還原。',
  'ollama.harness.prebuiltTag': '範例',
};

export default zh;
